// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.stm.domain.taxpayer.business.taxfree;

import com.stm.domain.taxpayer.business.taxfree.VdcDdc;
import javax.persistence.Entity;
import javax.persistence.Table;

privileged aspect VdcDdc_Roo_Jpa_Entity {
    
    declare @type: VdcDdc: @Entity;
    
    declare @type: VdcDdc: @Table(name = "taxpayer");
    
}
