// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.stm.domain.taxpayer;

import com.stm.domain.taxpayer.IncomeSourceFactoryIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect IncomeSourceFactoryIntegrationTest_Roo_Configurable {
    
    declare @type: IncomeSourceFactoryIntegrationTest: @Configurable;
    
}
