// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.stm.domain.taxpayer;

import com.stm.domain.taxpayer.IncomeSourceFactoryDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect IncomeSourceFactoryDataOnDemand_Roo_Configurable {
    
    declare @type: IncomeSourceFactoryDataOnDemand: @Configurable;
    
}
