// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.stm.domain.taxpayer.naturalperson.type;

import com.stm.domain.taxpayer.naturalperson.type.Spouse;
import javax.persistence.Entity;
import javax.persistence.Table;

privileged aspect Spouse_Roo_Jpa_Entity {
    
    declare @type: Spouse: @Entity;
    
    declare @type: Spouse: @Table(name = "taxpayer");
    
}
