// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.stm.domain.taxpayer.incomesource;

import com.stm.domain.taxpayer.incomesource.BusinessIncome;

privileged aspect BusinessIncome_Roo_JavaBean {
    
    public Double BusinessIncome.getServiceFees() {
        return this.serviceFees;
    }
    
    public void BusinessIncome.setServiceFees(Double serviceFees) {
        this.serviceFees = serviceFees;
    }
    
    public Double BusinessIncome.getAmountsDerivedFromDisposalOfTradingStock() {
        return this.amountsDerivedFromDisposalOfTradingStock;
    }
    
    public void BusinessIncome.setAmountsDerivedFromDisposalOfTradingStock(Double amountsDerivedFromDisposalOfTradingStock) {
        this.amountsDerivedFromDisposalOfTradingStock = amountsDerivedFromDisposalOfTradingStock;
    }
    
    public Double BusinessIncome.getNetGainsFromDisposalOfPersonBusinessAssets() {
        return this.netGainsFromDisposalOfPersonBusinessAssets;
    }
    
    public void BusinessIncome.setNetGainsFromDisposalOfPersonBusinessAssets(Double netGainsFromDisposalOfPersonBusinessAssets) {
        this.netGainsFromDisposalOfPersonBusinessAssets = netGainsFromDisposalOfPersonBusinessAssets;
    }
    
    public Double BusinessIncome.getAmountsTreatedAsDerivedFromDepreciableAssets() {
        return this.amountsTreatedAsDerivedFromDepreciableAssets;
    }
    
    public void BusinessIncome.setAmountsTreatedAsDerivedFromDepreciableAssets(Double amountsTreatedAsDerivedFromDepreciableAssets) {
        this.amountsTreatedAsDerivedFromDepreciableAssets = amountsTreatedAsDerivedFromDepreciableAssets;
    }
    
    public Double BusinessIncome.getGiftsReceivedByThePersonInRespect() {
        return this.giftsReceivedByThePersonInRespect;
    }
    
    public void BusinessIncome.setGiftsReceivedByThePersonInRespect(Double giftsReceivedByThePersonInRespect) {
        this.giftsReceivedByThePersonInRespect = giftsReceivedByThePersonInRespect;
    }
    
    public Double BusinessIncome.getAmountsDerivedAsConsiderationForAcceptingRestrictionOnCapacityToConductBusiness() {
        return this.amountsDerivedAsConsiderationForAcceptingRestrictionOnCapacityToConductBusiness;
    }
    
    public void BusinessIncome.setAmountsDerivedAsConsiderationForAcceptingRestrictionOnCapacityToConductBusiness(Double amountsDerivedAsConsiderationForAcceptingRestrictionOnCapacityToConductBusiness) {
        this.amountsDerivedAsConsiderationForAcceptingRestrictionOnCapacityToConductBusiness = amountsDerivedAsConsiderationForAcceptingRestrictionOnCapacityToConductBusiness;
    }
    
    public Double BusinessIncome.getAmountsDerivedFromInvestmentsEffectivelyConnectedWithBusiness() {
        return this.amountsDerivedFromInvestmentsEffectivelyConnectedWithBusiness;
    }
    
    public void BusinessIncome.setAmountsDerivedFromInvestmentsEffectivelyConnectedWithBusiness(Double amountsDerivedFromInvestmentsEffectivelyConnectedWithBusiness) {
        this.amountsDerivedFromInvestmentsEffectivelyConnectedWithBusiness = amountsDerivedFromInvestmentsEffectivelyConnectedWithBusiness;
    }
    
    public Double BusinessIncome.getAmountsIncludedByReasonOfChangeInAccountingSystem() {
        return this.amountsIncludedByReasonOfChangeInAccountingSystem;
    }
    
    public void BusinessIncome.setAmountsIncludedByReasonOfChangeInAccountingSystem(Double amountsIncludedByReasonOfChangeInAccountingSystem) {
        this.amountsIncludedByReasonOfChangeInAccountingSystem = amountsIncludedByReasonOfChangeInAccountingSystem;
    }
    
    public Double BusinessIncome.getAmountsIncludedByReasonOfTiming() {
        return this.amountsIncludedByReasonOfTiming;
    }
    
    public void BusinessIncome.setAmountsIncludedByReasonOfTiming(Double amountsIncludedByReasonOfTiming) {
        this.amountsIncludedByReasonOfTiming = amountsIncludedByReasonOfTiming;
    }
    
    public Double BusinessIncome.getExcessAmountReceivedByReasonOfExchangeRate() {
        return this.excessAmountReceivedByReasonOfExchangeRate;
    }
    
    public void BusinessIncome.setExcessAmountReceivedByReasonOfExchangeRate(Double excessAmountReceivedByReasonOfExchangeRate) {
        this.excessAmountReceivedByReasonOfExchangeRate = excessAmountReceivedByReasonOfExchangeRate;
    }
    
    public Double BusinessIncome.getRecoveredAmountOfBadDebtsDeductedEarlier() {
        return this.recoveredAmountOfBadDebtsDeductedEarlier;
    }
    
    public void BusinessIncome.setRecoveredAmountOfBadDebtsDeductedEarlier(Double recoveredAmountOfBadDebtsDeductedEarlier) {
        this.recoveredAmountOfBadDebtsDeductedEarlier = recoveredAmountOfBadDebtsDeductedEarlier;
    }
    
    public Double BusinessIncome.getAmountsIncludedAsPerContractOfCompletionBasis() {
        return this.amountsIncludedAsPerContractOfCompletionBasis;
    }
    
    public void BusinessIncome.setAmountsIncludedAsPerContractOfCompletionBasis(Double amountsIncludedAsPerContractOfCompletionBasis) {
        this.amountsIncludedAsPerContractOfCompletionBasis = amountsIncludedAsPerContractOfCompletionBasis;
    }
    
    public Double BusinessIncome.getDifferenceOfActualInterestAndInterestAsPerMarketRate() {
        return this.differenceOfActualInterestAndInterestAsPerMarketRate;
    }
    
    public void BusinessIncome.setDifferenceOfActualInterestAndInterestAsPerMarketRate(Double differenceOfActualInterestAndInterestAsPerMarketRate) {
        this.differenceOfActualInterestAndInterestAsPerMarketRate = differenceOfActualInterestAndInterestAsPerMarketRate;
    }
    
    public Double BusinessIncome.getAmountsPaidToThirdPerson() {
        return this.amountsPaidToThirdPerson;
    }
    
    public void BusinessIncome.setAmountsPaidToThirdPerson(Double amountsPaidToThirdPerson) {
        this.amountsPaidToThirdPerson = amountsPaidToThirdPerson;
    }
    
    public Double BusinessIncome.getAmountsDerivedAsCompensation() {
        return this.amountsDerivedAsCompensation;
    }
    
    public void BusinessIncome.setAmountsDerivedAsCompensation(Double amountsDerivedAsCompensation) {
        this.amountsDerivedAsCompensation = amountsDerivedAsCompensation;
    }
    
    public Double BusinessIncome.getOtherAmountsIncludedInProfitAndGains() {
        return this.otherAmountsIncludedInProfitAndGains;
    }
    
    public void BusinessIncome.setOtherAmountsIncludedInProfitAndGains(Double otherAmountsIncludedInProfitAndGains) {
        this.otherAmountsIncludedInProfitAndGains = otherAmountsIncludedInProfitAndGains;
    }
    
    public Double BusinessIncome.getTotalInclusions() {
        return this.totalInclusions;
    }
    
    public void BusinessIncome.setTotalInclusions(Double totalInclusions) {
        this.totalInclusions = totalInclusions;
    }
    
    public Double BusinessIncome.getInterest() {
        return this.interest;
    }
    
    public void BusinessIncome.setInterest(Double interest) {
        this.interest = interest;
    }
    
    public Double BusinessIncome.getCostOfTradingStocks() {
        return this.costOfTradingStocks;
    }
    
    public void BusinessIncome.setCostOfTradingStocks(Double costOfTradingStocks) {
        this.costOfTradingStocks = costOfTradingStocks;
    }
    
    public Double BusinessIncome.getRepairsAndImprovements() {
        return this.repairsAndImprovements;
    }
    
    public void BusinessIncome.setRepairsAndImprovements(Double repairsAndImprovements) {
        this.repairsAndImprovements = repairsAndImprovements;
    }
    
    public Double BusinessIncome.getPollutionControl() {
        return this.pollutionControl;
    }
    
    public void BusinessIncome.setPollutionControl(Double pollutionControl) {
        this.pollutionControl = pollutionControl;
    }
    
    public Double BusinessIncome.getResearchAndDevelopment() {
        return this.researchAndDevelopment;
    }
    
    public void BusinessIncome.setResearchAndDevelopment(Double researchAndDevelopment) {
        this.researchAndDevelopment = researchAndDevelopment;
    }
    
    public Double BusinessIncome.getDepreciation() {
        return this.depreciation;
    }
    
    public void BusinessIncome.setDepreciation(Double depreciation) {
        this.depreciation = depreciation;
    }
    
    public Double BusinessIncome.getDeductibleReserve() {
        return this.deductibleReserve;
    }
    
    public void BusinessIncome.setDeductibleReserve(Double deductibleReserve) {
        this.deductibleReserve = deductibleReserve;
    }
    
    public Double BusinessIncome.getOtherDeductibleExpense() {
        return this.otherDeductibleExpense;
    }
    
    public void BusinessIncome.setOtherDeductibleExpense(Double otherDeductibleExpense) {
        this.otherDeductibleExpense = otherDeductibleExpense;
    }
    
    public Double BusinessIncome.getTaxPaidOutsideNepal() {
        return this.taxPaidOutsideNepal;
    }
    
    public void BusinessIncome.setTaxPaidOutsideNepal(Double taxPaidOutsideNepal) {
        this.taxPaidOutsideNepal = taxPaidOutsideNepal;
    }
    
    public Double BusinessIncome.getTotalDeductibleExpense() {
        return this.totalDeductibleExpense;
    }
    
    public void BusinessIncome.setTotalDeductibleExpense(Double totalDeductibleExpense) {
        this.totalDeductibleExpense = totalDeductibleExpense;
    }
    
    public Double BusinessIncome.getLosesTransferredFromOtherBusiness() {
        return this.losesTransferredFromOtherBusiness;
    }
    
    public void BusinessIncome.setLosesTransferredFromOtherBusiness(Double losesTransferredFromOtherBusiness) {
        this.losesTransferredFromOtherBusiness = losesTransferredFromOtherBusiness;
    }
    
    public Double BusinessIncome.getCarriedForwardOfUnrelievedLosses() {
        return this.carriedForwardOfUnrelievedLosses;
    }
    
    public void BusinessIncome.setCarriedForwardOfUnrelievedLosses(Double carriedForwardOfUnrelievedLosses) {
        this.carriedForwardOfUnrelievedLosses = carriedForwardOfUnrelievedLosses;
    }
    
    public Double BusinessIncome.getTotalDeductibleLoss() {
        return this.totalDeductibleLoss;
    }
    
    public void BusinessIncome.setTotalDeductibleLoss(Double totalDeductibleLoss) {
        this.totalDeductibleLoss = totalDeductibleLoss;
    }
    
    public Double BusinessIncome.getTotalDeduction() {
        return this.totalDeduction;
    }
    
    public void BusinessIncome.setTotalDeduction(Double totalDeduction) {
        this.totalDeduction = totalDeduction;
    }
    
    public Double BusinessIncome.getIncomeOrLossFromBusiness() {
        return this.incomeOrLossFromBusiness;
    }
    
    public void BusinessIncome.setIncomeOrLossFromBusiness(Double incomeOrLossFromBusiness) {
        this.incomeOrLossFromBusiness = incomeOrLossFromBusiness;
    }
    
    public Double BusinessIncome.getLossTransferredToOtherBusiness() {
        return this.lossTransferredToOtherBusiness;
    }
    
    public void BusinessIncome.setLossTransferredToOtherBusiness(Double lossTransferredToOtherBusiness) {
        this.lossTransferredToOtherBusiness = lossTransferredToOtherBusiness;
    }
    
    public Double BusinessIncome.getTotalIncomeOrLossFromBusiness() {
        return this.totalIncomeOrLossFromBusiness;
    }
    
    public void BusinessIncome.setTotalIncomeOrLossFromBusiness(Double totalIncomeOrLossFromBusiness) {
        this.totalIncomeOrLossFromBusiness = totalIncomeOrLossFromBusiness;
    }
    
}
