// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.stm.domain.taxpayer.incomesource;

import com.stm.domain.taxpayer.incomesource.Investment;

privileged aspect Investment_Roo_JavaBean {
    
    public Double Investment.getDividends() {
        return this.dividends;
    }
    
    public void Investment.setDividends(Double dividends) {
        this.dividends = dividends;
    }
    
    public Double Investment.getGainFromInvestmentInsuranceOtherThanFinalWithholding() {
        return this.gainFromInvestmentInsuranceOtherThanFinalWithholding;
    }
    
    public void Investment.setGainFromInvestmentInsuranceOtherThanFinalWithholding(Double gainFromInvestmentInsuranceOtherThanFinalWithholding) {
        this.gainFromInvestmentInsuranceOtherThanFinalWithholding = gainFromInvestmentInsuranceOtherThanFinalWithholding;
    }
    
    public Double Investment.getInterestsOtherThanFinalWithholding() {
        return this.interestsOtherThanFinalWithholding;
    }
    
    public void Investment.setInterestsOtherThanFinalWithholding(Double interestsOtherThanFinalWithholding) {
        this.interestsOtherThanFinalWithholding = interestsOtherThanFinalWithholding;
    }
    
    public Double Investment.getRentOtherThanFinalWithholding() {
        return this.rentOtherThanFinalWithholding;
    }
    
    public void Investment.setRentOtherThanFinalWithholding(Double rentOtherThanFinalWithholding) {
        this.rentOtherThanFinalWithholding = rentOtherThanFinalWithholding;
    }
    
    public Double Investment.getPymentForNaturalResourceOtherThanFinalWithholding() {
        return this.pymentForNaturalResourceOtherThanFinalWithholding;
    }
    
    public void Investment.setPymentForNaturalResourceOtherThanFinalWithholding(Double pymentForNaturalResourceOtherThanFinalWithholding) {
        this.pymentForNaturalResourceOtherThanFinalWithholding = pymentForNaturalResourceOtherThanFinalWithholding;
    }
    
    public Double Investment.getRoyalties() {
        return this.royalties;
    }
    
    public void Investment.setRoyalties(Double royalties) {
        this.royalties = royalties;
    }
    
    public Double Investment.getUnapprovedRetirementFundOtherThanWithholding() {
        return this.unapprovedRetirementFundOtherThanWithholding;
    }
    
    public void Investment.setUnapprovedRetirementFundOtherThanWithholding(Double unapprovedRetirementFundOtherThanWithholding) {
        this.unapprovedRetirementFundOtherThanWithholding = unapprovedRetirementFundOtherThanWithholding;
    }
    
    public Double Investment.getDisposalOfDepreciableAssets() {
        return this.disposalOfDepreciableAssets;
    }
    
    public void Investment.setDisposalOfDepreciableAssets(Double disposalOfDepreciableAssets) {
        this.disposalOfDepreciableAssets = disposalOfDepreciableAssets;
    }
    
    public Double Investment.getGiftsReveivedByPersonInRespectOfInvestment() {
        return this.giftsReveivedByPersonInRespectOfInvestment;
    }
    
    public void Investment.setGiftsReveivedByPersonInRespectOfInvestment(Double giftsReveivedByPersonInRespectOfInvestment) {
        this.giftsReveivedByPersonInRespectOfInvestment = giftsReveivedByPersonInRespectOfInvestment;
    }
    
    public Double Investment.getRetirementPaymentAlongWithPaymentsRetirementContributions() {
        return this.retirementPaymentAlongWithPaymentsRetirementContributions;
    }
    
    public void Investment.setRetirementPaymentAlongWithPaymentsRetirementContributions(Double retirementPaymentAlongWithPaymentsRetirementContributions) {
        this.retirementPaymentAlongWithPaymentsRetirementContributions = retirementPaymentAlongWithPaymentsRetirementContributions;
    }
    
    public Double Investment.getAmountsDerivedAsConsiderationForAcceptingRestrictionOfInvestment() {
        return this.amountsDerivedAsConsiderationForAcceptingRestrictionOfInvestment;
    }
    
    public void Investment.setAmountsDerivedAsConsiderationForAcceptingRestrictionOfInvestment(Double amountsDerivedAsConsiderationForAcceptingRestrictionOfInvestment) {
        this.amountsDerivedAsConsiderationForAcceptingRestrictionOfInvestment = amountsDerivedAsConsiderationForAcceptingRestrictionOfInvestment;
    }
    
    public Double Investment.getAmountsIncludedByReasonOfTiming() {
        return this.amountsIncludedByReasonOfTiming;
    }
    
    public void Investment.setAmountsIncludedByReasonOfTiming(Double amountsIncludedByReasonOfTiming) {
        this.amountsIncludedByReasonOfTiming = amountsIncludedByReasonOfTiming;
    }
    
    public Double Investment.getExcessAmountReceivedByReasonOfExchangeRate() {
        return this.excessAmountReceivedByReasonOfExchangeRate;
    }
    
    public void Investment.setExcessAmountReceivedByReasonOfExchangeRate(Double excessAmountReceivedByReasonOfExchangeRate) {
        this.excessAmountReceivedByReasonOfExchangeRate = excessAmountReceivedByReasonOfExchangeRate;
    }
    
    public Double Investment.getRecoveredAmountOfBadDebtsDeductedEarlier() {
        return this.recoveredAmountOfBadDebtsDeductedEarlier;
    }
    
    public void Investment.setRecoveredAmountOfBadDebtsDeductedEarlier(Double recoveredAmountOfBadDebtsDeductedEarlier) {
        this.recoveredAmountOfBadDebtsDeductedEarlier = recoveredAmountOfBadDebtsDeductedEarlier;
    }
    
    public Double Investment.getDifferenceOfActualInterestAndInterestAsPerMarketRate() {
        return this.differenceOfActualInterestAndInterestAsPerMarketRate;
    }
    
    public void Investment.setDifferenceOfActualInterestAndInterestAsPerMarketRate(Double differenceOfActualInterestAndInterestAsPerMarketRate) {
        this.differenceOfActualInterestAndInterestAsPerMarketRate = differenceOfActualInterestAndInterestAsPerMarketRate;
    }
    
    public Double Investment.getAmountsPaidToThirdPersonInsteadOfActualPayee() {
        return this.amountsPaidToThirdPersonInsteadOfActualPayee;
    }
    
    public void Investment.setAmountsPaidToThirdPersonInsteadOfActualPayee(Double amountsPaidToThirdPersonInsteadOfActualPayee) {
        this.amountsPaidToThirdPersonInsteadOfActualPayee = amountsPaidToThirdPersonInsteadOfActualPayee;
    }
    
    public Double Investment.getAmountsDerivedFromJointOwnershipInvestment() {
        return this.amountsDerivedFromJointOwnershipInvestment;
    }
    
    public void Investment.setAmountsDerivedFromJointOwnershipInvestment(Double amountsDerivedFromJointOwnershipInvestment) {
        this.amountsDerivedFromJointOwnershipInvestment = amountsDerivedFromJointOwnershipInvestment;
    }
    
    public Double Investment.getAmountsDerivedAsCompensation() {
        return this.amountsDerivedAsCompensation;
    }
    
    public void Investment.setAmountsDerivedAsCompensation(Double amountsDerivedAsCompensation) {
        this.amountsDerivedAsCompensation = amountsDerivedAsCompensation;
    }
    
    public Double Investment.getOtherAmountsIncludedInProfitAndGains() {
        return this.otherAmountsIncludedInProfitAndGains;
    }
    
    public void Investment.setOtherAmountsIncludedInProfitAndGains(Double otherAmountsIncludedInProfitAndGains) {
        this.otherAmountsIncludedInProfitAndGains = otherAmountsIncludedInProfitAndGains;
    }
    
    public Double Investment.getTotalOfAbove19Rows() {
        return this.totalOfAbove19Rows;
    }
    
    public void Investment.setTotalOfAbove19Rows(Double totalOfAbove19Rows) {
        this.totalOfAbove19Rows = totalOfAbove19Rows;
    }
    
    public Double Investment.getInterest() {
        return this.Interest;
    }
    
    public void Investment.setInterest(Double Interest) {
        this.Interest = Interest;
    }
    
    public Double Investment.getRepairsAndImprovements() {
        return this.repairsAndImprovements;
    }
    
    public void Investment.setRepairsAndImprovements(Double repairsAndImprovements) {
        this.repairsAndImprovements = repairsAndImprovements;
    }
    
    public Double Investment.getDepreciation() {
        return this.depreciation;
    }
    
    public void Investment.setDepreciation(Double depreciation) {
        this.depreciation = depreciation;
    }
    
    public Double Investment.getOtherDeductibleExpenses() {
        return this.otherDeductibleExpenses;
    }
    
    public void Investment.setOtherDeductibleExpenses(Double otherDeductibleExpenses) {
        this.otherDeductibleExpenses = otherDeductibleExpenses;
    }
    
    public Double Investment.getTotalDeductibleExpenses() {
        return this.totalDeductibleExpenses;
    }
    
    public void Investment.setTotalDeductibleExpenses(Double totalDeductibleExpenses) {
        this.totalDeductibleExpenses = totalDeductibleExpenses;
    }
    
    public Double Investment.getLossesTransferredFromOtherBusinessOrInvestment() {
        return this.lossesTransferredFromOtherBusinessOrInvestment;
    }
    
    public void Investment.setLossesTransferredFromOtherBusinessOrInvestment(Double lossesTransferredFromOtherBusinessOrInvestment) {
        this.lossesTransferredFromOtherBusinessOrInvestment = lossesTransferredFromOtherBusinessOrInvestment;
    }
    
    public Double Investment.getCarriedForwardOfUnrelivedBusinessLosses() {
        return this.carriedForwardOfUnrelivedBusinessLosses;
    }
    
    public void Investment.setCarriedForwardOfUnrelivedBusinessLosses(Double carriedForwardOfUnrelivedBusinessLosses) {
        this.carriedForwardOfUnrelivedBusinessLosses = carriedForwardOfUnrelivedBusinessLosses;
    }
    
    public Double Investment.getTotalDeductibleLoses() {
        return this.totalDeductibleLoses;
    }
    
    public void Investment.setTotalDeductibleLoses(Double totalDeductibleLoses) {
        this.totalDeductibleLoses = totalDeductibleLoses;
    }
    
    public Double Investment.getTotalDeductions() {
        return this.totalDeductions;
    }
    
    public void Investment.setTotalDeductions(Double totalDeductions) {
        this.totalDeductions = totalDeductions;
    }
    
    public Double Investment.getIncomeOrLossFromInvestment() {
        return this.incomeOrLossFromInvestment;
    }
    
    public void Investment.setIncomeOrLossFromInvestment(Double incomeOrLossFromInvestment) {
        this.incomeOrLossFromInvestment = incomeOrLossFromInvestment;
    }
    
    public Double Investment.getLossTransferredToOtherInvestmentIncome() {
        return this.lossTransferredToOtherInvestmentIncome;
    }
    
    public void Investment.setLossTransferredToOtherInvestmentIncome(Double lossTransferredToOtherInvestmentIncome) {
        this.lossTransferredToOtherInvestmentIncome = lossTransferredToOtherInvestmentIncome;
    }
    
    public Double Investment.getTotalIncomeOrLossFromInvestment() {
        return this.totalIncomeOrLossFromInvestment;
    }
    
    public void Investment.setTotalIncomeOrLossFromInvestment(Double totalIncomeOrLossFromInvestment) {
        this.totalIncomeOrLossFromInvestment = totalIncomeOrLossFromInvestment;
    }
    
}
