// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.stm.domain.taxpayer.business;

import com.stm.domain.taxpayer.business.Bank;
import javax.persistence.Entity;
import javax.persistence.Table;

privileged aspect Bank_Roo_Jpa_Entity {
    
    declare @type: Bank: @Entity;
    
    declare @type: Bank: @Table(name = "taxpayer");
    
}
