// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.stm.domain.taxpayer.incomesource.nonbusinesschargable;

import com.stm.domain.taxpayer.incomesource.nonbusinesschargable.SharesDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect SharesDataOnDemand_Roo_Configurable {
    
    declare @type: SharesDataOnDemand: @Configurable;
    
}
