// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.stm.domain;

import com.stm.domain.Auditor;
import javax.persistence.Entity;
import javax.persistence.Table;

privileged aspect Auditor_Roo_Jpa_Entity {
    
    declare @type: Auditor: @Entity;
    
    declare @type: Auditor: @Table(name = "auditor");
    
}
