// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.stm.domain.taxpayer.incomesource;

import com.stm.domain.taxpayer.incomesource.ExemptIncomeDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ExemptIncomeDataOnDemand_Roo_Configurable {
    
    declare @type: ExemptIncomeDataOnDemand: @Configurable;
    
}
